### ISSUE TITLE
Switch the Input values from directory to Pandas dataframe

### ISSUE THREAD

**Issue by cgkoros** [philos123/tr_following#2]
Hi,
I believe this code is interesting!
Do you know which part of the code I need to change because I want to read from a Pandas DataFrame instead of a directory?
(I don't have knowledge in Python or finance, and I'm trying to experiment with this code)

If you could this I believe that it will be more usefull this code because We could use real data in real time .. :)

**Comment by philippe-ostiguy** [comment]
Hi,

Thank you for the comment.

As for reading from a Pandas DataFrame, you still need to read it from a data storage system (CSV, SQL database, etc.). A Pandas DataFrame is used to manipulate the data. This is what the code is doing at the moment: reading CSV files from the directory and loading them into a DataFrame.

As for real-time, it's not designed for that at the moment.

If you want to play with the code (and read the data differently), you can find it in init_operations.py, and within that, the functions.

```
def init_series(self):
        """Function that extract the data from csv to a pandas Dataframe self.series. It actually is the data that we are using for the strategy """

        self.series = md.csv_to_pandas(self.date_name, self.start_date, self.end_date, self.name, self.directory,
                            self.asset, ordinal_name=self.date_ordinal_name, is_fx=self.is_fx, dup_col = self.dup_col)

        if self.is_detrend:
            self.series_diff = md.de_trend(self.series,self.date_name, self.date_ordinal_name,self.default_data,
                                           period=self.period,p_value= self.p_value)
```
